### ISSUE TITLE
Error when running the RM command

### ISSUE THREAD

**Issue by grytveten** [oslocyclotronlab/oslo-method-software#10]
Some of the summer students get an error "Cannot find response function" when they try to generate a response matrix.

**Comment by fzeiser** [comment]
I didn't experience it myself -- but during lunch today I was told that it works anyhow. So it should be treated as a erroneous warning, not an error.

**Comment by fzeiser** [comment]
Gry says that I got it wrong: The created resp matrix is filled with banana entries -- so we might want to fix the error if it reoccurs!

**Comment by cecgresonant** [comment]
It seems like this is an obsolete issue with no new reoccurrence (or ways to reproduce the error).
