### ISSUE TITLE
Chi2 fit to Temperature & uncertainty determination

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/oslo-method-software#11]
Currently, so 99443fe03c90e3032b96e089767394f48bc555a0, in counting supports to print the chi2 deviation for different temperature interpolations T when using the CT formula.

They are printed in following loop:
https://github.com/oslocyclotronlab/oslo-method-software/blob/dd5150028a66b99d468408b01851761e02f4576e/prog/counting.c#L690-L695

However, there is a bug! What is printed is not chi2, but chi2_red = chi2/nfree. This can be seen "at the end of" the function anchorH, see 
https://github.com/oslocyclotronlab/oslo-method-software/blob/dd5150028a66b99d468408b01851761e02f4576e/prog/counting.c#L1682-L1692

**Comment by fzeiser** [comment]
Now, there is two sensible options:
i) Print chi²
ii) Print chi²_red

I would vote up for option 1, because I think that this should be how we could derive the uncertainty for T "graphically".

See for example:
The Minimum Chi-Square Method, by Wall1996 
Online version: https://ned.ipac.caltech.edu/level5/Wall2/Wal3_4.html
Where we would regard v=1.

Similarly, we find in Press1992, Numerical Recipes in C: The Art of Scientific Computing, p.696
> As a first example, let us consider the case ν = 1, where we want to find
> the confidence interval of a single parameter, say a 1 . Notice that the chi-square
> distribution with ν = 1 degree of freedom is the same distribution as that of the square
> of a single normally distributed quantity. Thus ∆χ 2 ν < 1 occurs 68.3 percent of the
> time (1-σ for the normal distribution), ∆χ 2 ν < 4 occurs 95.4 percent of the time (2-σ
> for the normal distribution), ∆χ 2 ν < 9 occurs 99.73 percent of the time (3-σ for the
> normal distribution), etc. In this manner you find the ∆χ 2 ν that corresponds to your
> desired confidence level. (Additional values are given in the accompanying table.)

**Comment by fzeiser** [comment]
After a discussion with AC, I attach a script that shows how the different method compare against the error estimation of curve_fit:

https://gist.github.com/fzeiser/f8c8741e8fde0311f4ad0918a5c672cb

See following plots

![chi2](https://user-images.githubusercontent.com/15156776/42581422-00af7804-852d-11e8-95d8-f61f4cbd4109.png)
![data](https://user-images.githubusercontent.com/15156776/42581425-012fc45a-852d-11e8-8554-8115b7852b5c.png)

![chi2red](https://user-images.githubusercontent.com/15156776/42581423-00d4755a-852d-11e8-9861-2cb9cf4292d9.png)
![chi2red_norm](https://user-images.githubusercontent.com/15156776/42581424-00ff1832-852d-11e8-80de-6726fb9e9699.png)

**Comment by fzeiser** [comment]
@cecgresonant: In principal the same text as in Wall1996 (see above) it reproduced in following book chaper:
J. V. Wall, University of British Columbia, Vancouver, C. R. Jenkins 
6 - Data modelling and parameter estimation: basics (pp 126-150)
section: 6.3 The minimum chi-square method
https://doi.org/10.1017/CBO9781139031998.010
It's a quite nice book and available via the university library.

**Comment by cecgresonant** [comment]
Hi, I agree that the best would be to print *both* the reduced chi^2 and the chi^2 itself in counting.c. The reduced chi^2 gives a measure of how well behaved the fit is, and the chi^2 is needed for the uncertainty estimate.

After some reading and thinking, I am also convinced that the standard deviation should be estimated from the chi^2 and *not* the reduced chi^2. Intuitively, this seems the right way to do it, because if N_free = 1000, the relative error should be smaller than if N_free=10. But if one uses the reduced chi^2 probably the error is overestimated for N_free=1000 compared to N_free = 10.
