### ISSUE TITLE
Spin-cutoff interpolation / extrapolation

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/oslo-method-software#17]
I wondered how exactly the spin cutoff should be interpolated -- or rather extrapolated. If one uses option 5, the interpolation between discretes and EB05, and we use a linear extrapolation, we can get negative (spin-cuts^2). Say you evaluate the spin-cut at `Ex_disc=1 MeV`, should the spin-cut `sigma2` below 1 MeV be set to `sigma2(Ex_disc)`? 

Looking at the code, it seems to me that this is not what is done, but instead we (always) set an arbitrary minimum at `sigma2=0.5`, right? 
https://github.com/oslocyclotronlab/oslo-method-software/blob/6558edba7ff1c6abd9c8b95ff23b5b533eba7cd0/prog/counting.c#L1028

@magneg : Can you shed some light on this?

**Comment by magneg** [comment]
Yes, the lowest value for sigma is sqrt(0.5)
