### ISSUE TITLE
Response function: wrong energy for compton edge

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/oslo-method-software#19]
It seems like the Compton edge is calculated at the wrong energy. It should be at backscattering, θ=180 deg, so π/2, not at π. 

https://github.com/oslocyclotronlab/oslo-method-software/blob/d559925ac96cc0264c9f1711085ca780198be073/mama/src/libs/gf2/folding.f#L2538-L2543

check also processing further down:
https://github.com/oslocyclotronlab/oslo-method-software/blob/d559925ac96cc0264c9f1711085ca780198be073/mama/src/libs/gf2/folding.f#L2577-L2587

@magneg: Could you confirm this? It's sometimes a lot of things "going on" in mama, but I think this should be corrected.

**Comment by magneg** [comment]
Not sure about this, is not pi = 180 dgr?

**Comment by fzeiser** [comment]
For some reason I don't see an impact of changing this, but it might be connected to https://github.com/oslocyclotronlab/ompy/issues/131#issuecomment-644554583: The fan interpolation seems to interpolate also above Ecompton.

**Comment by fzeiser** [comment]
> Not sure about this, is not pi = 180 dgr?

Haha, I must have been very sleepy today ;P! You're right! There is no issue at all with this routine!

**Comment by magneg** [comment]
It should, even above full-energy peak due to detector resolution...
