### ISSUE TITLE
Response function: indices for single & double escape slightly off?

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/oslo-method-software#20]
I wondered whether the indices for the single and double escape are slightly off in the response as of c2662c2295a37440d747f090551dc9bd5ecc785f.

I created a response matrix for cactus (option 3) "for unfolding", so with the reduced fwhm (option 10, 6.8%). 

> Dimension of response-matrix < 512>:
> Cal. coeff. a0 (keV)     <    -6.8>:
> Cal. coeff. a1 (keV/ch)  <    20.6>:

The following figure shows a projection at the energy bin close to 6140 keV.
The full energy peak here is at `6143`. Thus, I would expect the single and double escape peaks at `6143 - 511 = 5632` and `6143 - 2*511 = 5121` keV, but in `mama` they are at `5649` and `5155` keV

![image](https://user-images.githubusercontent.com/15156776/84774837-ad1a3d80-afde-11ea-8c4d-4c3113ec02c3.png)

@magneg: I don't expect this to have a major impact, but it might be worth having a look at it, once you have time for this.

**Comment by magneg** [comment]
Hei Fabio,

veldig fint at du fant denne feilen. Det var en tid jeg kjempet for å få god tilpassning like under full-energi området.
Alle tallene her skulle være 511 eller 1022, men du ser for f.eks for 6130 har jeg 500 og 995. Skal rette opp å legge ut riktig.

Tusen takk,
hilsen Magne



      DATA ER3/   360.,   847.,   1238.,   1779., 2839., 3089.,
     +           4497.,  6130.,   9900.,  15000.,              0,0,0,0,0,0,0,0,0,0,
     +    0,0,0,0,0,0,0,0,0,0/
      DATA ESE3/  511.,   511.,    511.,    505.,  491.,  490.,
     +            493.,   500.,    511.,    511.,              0,0,0,0,0,0,0,0,0,0,
     +    0,0,0,0,0,0,0,0,0,0/
      DATA EDE3/ 1022.,  1030.,   1022.,   1022.,  994.,  985.,
     +            982.,   995.,   1050.,   1022.,              0,0,0,0,0,0,0,0,0,0,
     +    0,0,0,0,0,0,0,0,0,0/

**Comment by magneg** [comment]
Nå ser det bedre ut med energier (7 keV bins lager noe avvik):

Fitted chs  713 to  920       3 Peaks
  12 indept. pars    196 degrees of freedom weighted with fit.
   2 iterations,  Chisq/d.o.f.=  0.000
Background and shape parameters:
A=     -0.00+-   15.02 B=   0.0000+-  0.0368 C=  -0.0000+-  0.0000
R=    10.00+-    0.00 Beta=    1.749+-   0.000 Step=  0.25+-  0.00
Peak     Width           Area     Centroid   Energy(keV)  Fwhm(keV)
 1   3.19( 37.31)        0(    3)  879.86  6159.02(248.68)   22.3
 2   3.39( 81.20)        0(    3)  806.86  5647.99(541.01)   23.7
 3   2.91(857.84)        0(    3)  733.88  5137.18(******)   20.4


[cid:B2DF4A9A-3421-4661-8680-889D864460E0@lan]

**Comment by fzeiser** [comment]
Closed in 4a2ac828f3995a135e0d2ec7bb714d3e1e9aa895
