### ISSUE TITLE
Not needed

### ISSUE THREAD

**Issue by vetlewi** [oslocyclotronlab/oslo-method-software#9]
In the README file it says that https://github.com/oslocyclotronlab/oslo-method-software#root-for-mac:
```
export LC_ALL="C" 
export LANG="en_US" 
export TERM=xterm-color

PS1='$USER@\H:\W>'
```
is required for Mac. However I have never needed to add it, so I think this only applies to old versions of macOS/OS X

**Comment by jorgenem** [comment]
This readme really could use some tidying up! I vote for removing.

**Comment by fzeiser** [comment]
Don't see either why you should need this for root! Agree with both of you.

**Comment by fzeiser** [comment]
Isn't this here also old stuff to be removed?
https://github.com/oslocyclotronlab/oslo-method-software/blob/ae07ea41dea882fea4eb7e01f83088e4bf865566/README.md#L163-L170

Rather follow the description above:
https://github.com/oslocyclotronlab/oslo-method-software/blob/ae07ea41dea882fea4eb7e01f83088e4bf865566/README.md#L145

**Comment by cecgresonant** [comment]
This is indeed very old and in fact the lines you highlight have nothing to do with Root at all. They were just my old .bashrc commands to fix the style of the terminal window (OS 10.5, if I remember correctly). I have no idea how they ended up being connected to the Root for Mac description. 

However, something like the following lines should be included in the .bash_profile if Root is manually installed (I think the .bashrc is not used anymore): 
# For ROOT v6.12.06
export ROOTSYS=/Applications/root-v6.12.06-build                
export PATH=$ROOTSYS/bin:$PATH
export LD_LIBRARY_PATH=$ROOTSYS/lib:$LD_LIBRARY_PATH
export LDYLD_LIBRARY_PATH=$ROOTSYS/lib:$DYLD_LIBRARY_PATH


Cheers,
Cecilie

Ann-Cecilie Larsen
Researcher, Oslo Cyclotron Laboratory
Department of Physics
University of Oslo
P.O.Box 1048 Blindern
N-0316 Oslo, Norway

Office: +47 22 85 54 86
Fax: +47 22 85 64 22
E-mail: a.c.larsen@fys.uio.no
Twitter: @Cec_gRESONANT

**Comment by grytveten** [comment]
I have more or less always followed the ROOT instructions for installing (by compiling from source) and I have not since many, many versions ago had to anything but source the thisroot file that comes together with ROOT. I think it is safe to remove these lines from the README.

________________________________

**Comment by cecgresonant** [comment]
This is true, then I think one can just add

alias thisroot=". bin/thisroot.sh"

Much more short and nice than my old stuff :)
 
Ann-Cecilie Larsen
Researcher, Oslo Cyclotron Laboratory
Department of Physics
University of Oslo
P.O.Box 1048 Blindern
N-0316 Oslo, Norway

Office: +47 22 85 54 86
Fax: +47 22 85 64 22
E-mail: a.c.larsen@fys.uio.no
Twitter: @Cec_gRESONANT

**Comment by fzeiser** [comment]
> This is true, then I think one can just add alias thisroot=". bin/thisroot.sh" 

I can't follow completely, why you should alias.
If you follow the description in the README (which is in that pint equivalent to CERN root's recommendation), you will source the 'thisroot.sh' script. This takes all the troubles from you of settings environment variables manually.
